### ISSUE TITLE
Can't consume AA.js from nom

### ISSUE THREAD

**Issue by gmarty** [onekiloparsec/aa-js#14]
Hey, excellent project! I'm trying to integrate in a personal project built on node.js.
I can't do that out of the box because only the `src/` folder is distributed via npm (node doesn't support es modules at this time). So I have to build it using rollup:
```bash
$ rollup node_modules/aa.js/src/index.js --file aa.js/index.js --format cjs
```

Then I can import it doing:
```js
const { moon } = require("./aa.js");
```

It's obviously not ideal. I can see a webpack configuration, but the resulting files should be added to npm and a new version of the package published.

**Comment by onekiloparsec** [comment]
Thanks for your message. I agree this is far from ideal. I must say I struggle a lot with all these config stuff (webpack, rollup or whatever). Would you be able to fix this and make a PR?

**Comment by onekiloparsec** [comment]
Hi @gmarty I just published a new version (0.10) using a completely new (and a lot simpler) webpack config. A dist minified file is now included in the package. Please, git it a try, and let me know!

**Comment by gmarty** [comment]
That looks great, I didn't have time to work on a pull request. I assume the work was done in the `develop` branch.
Now, you need to republish a new version of the package using something like [`npm publish`](https://docs.npmjs.com/cli/publish). The latest version you published was 0.3.6 (See [your package entry on npm website](https://www.npmjs.com/package/aa.js)). Let me know if you need any help!

**Comment by onekiloparsec** [comment]
The development process of that package is a bit messy, I am sorry. The branch `develop` is just brand new because I wanted to throw some new imported stuff that will come later. Since I wanted to fix that import thing rapidly, I worked directly on `master`.

Anyway, one of the consequences of that messy and not-really well made process, the package is actually published under another name since quite a while! Here it is:

https://www.npmjs.com/package/astronomical-algorithms

I'll update the Readme and the npm website, sorry!

**Comment by onekiloparsec** [comment]
The README is updated, and the package 'aa.js' is deprecated in the npm registry.
